FROM node:latest

# Create app directory
WORKDIR /server

# Install app dependencies
COPY package*.json ./

RUN npm install

# Copying rest of the application to app directory
COPY . /server

# Expose the port and start the application
EXPOSE $PORT

CMD ["npm", "run", "dev"]
