version: '3.8'

services:
  csci-331-project:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    volumes: 
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    container_name: node-server
    expose: 
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
    links:
      - mongo-db
  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db

