POST  http://localhost:5000/apidb HTTP/1.1
content-type: application/json

[ 1, 0, 2, 10, 3, 20, 4, 30 ]
###

# Gets all times from database
GET   http://localhost:5000/apidb HTTP/1.1
content-type: application/json

###

# Sets up new database from scratch
GET  http://localhost:5000/setup HTTP/1.1
content-type: application/json

###

### Correct Username and Pass
POST  http://localhost:5000/login HTTP/1.1
content-type: application/json

{ "email": "gage", 
"password": "pass" }
###

### Incorrect Username and Pass
POST  http://localhost:5000/login HTTP/1.1
content-type: application/json

{ "email": "gage", 
"password": "pass" }
###



### Register
POST  http://localhost:5000/register HTTP/1.1
content-type: application/json

{ "first": "gage",
"last": "halverson",
"email": "gage", 
"password": "pass" }
###
