POST  http://localhost:5000/apidb HTTP/1.1
content-type: application/json

# [ 7, 45, 7, 0, 6, 30, 6, 0 ]
[ 1, 0, 2, 10, 3, 20, 4, 30 ]
###


GET   http://localhost:5000/apidb HTTP/1.1
content-type: application/json

###

GET  http://localhost:5000/setup HTTP/1.1
content-type: application/json

###

### Correct Username and Pass
POST  http://localhost:5000/login HTTP/1.1
content-type: application/json

{ "email": "gage", 
"password": "pass" }
###

### Incorrect Username and Pass
POST  http://localhost:5000/login HTTP/1.1
content-type: application/json

{ "email": "gage1", 
"password": "pass" }
###